#!/usr/bin/env python3
from __future__ import annotations

import json
import shutil
from pathlib import Path
from typing import Any

try:
    from tools.alpha4_binding_graph import parse_seed_bindings
    from tools.alpha4_operational_expression import derive_operational_graphs
except ModuleNotFoundError:
    from alpha4_binding_graph import parse_seed_bindings
    from alpha4_operational_expression import derive_operational_graphs

ROOT = Path(__file__).resolve().parents[1]


def _records(root: Path) -> list[dict[str, Any]]:
    bindings = parse_seed_bindings(root)
    pair_by_id = {item.component_id: item for item in bindings.pairs}
    graphs = derive_operational_graphs(root)
    records: list[dict[str, Any]] = []
    for component in graphs["components"]:
        component_id = str(component["component_id"])
        pair = pair_by_id[component_id]
        nodes = component["nodes"]
        rin = next(
            str(node["value"]) for node in nodes if node["op"] == "CHECK_RECOGNITION"
        )
        set_values = [
            str(node["value"]) for node in nodes if node["op"] == "SET_RECOGNITION"
        ]
        rout = set_values[0] if set_values else rin
        ops = {str(node["op"]) for node in nodes}
        if "ADD_EVIDENCE" in ops:
            kind = "OBSERVE_EVIDENCE"
        elif "SET_RECOGNITION" in ops:
            kind = "RECOGNIZE"
        else:
            kind = "PRESERVE"
        records.append(
            {
                "component_id": component_id,
                "operational_word": pair.operational_word,
                "formal_operator": pair.formal_operator,
                "recognition_in": rin,
                "recognition_out": rout,
                "operation_kind": kind,
                "authority_requirement": (
                    "LOCAL_EXACT_SUBJECT_EVIDENCE"
                    if "REQUIRE_LOCAL_AUTHORITY_WITNESS" in ops
                    else "NONE"
                ),
                "nodes": [
                    {key: node[key] for key in ("op", "value") if key in node}
                    for node in nodes
                ],
            }
        )
    return records


def write_english(target: Path, records: list[dict[str, Any]]) -> None:
    lines = [
        "# ASET Seed 0.4alpha — generated release companion",
        "",
        "Generated by release CI. Seed membership: external companion. Semantic precedence: none.",
        "",
    ]
    for item in records:
        lines += [
            f"### {item['component_id']}",
            f"Operational: `{item['operational_word']}`",
            f"Relational: `{item['formal_operator']}`",
            f"Recognition: `{item['recognition_in']} -> {item['recognition_out']}`",
            f"Operation: `{item['operation_kind']}`",
            f"Authority: `{item['authority_requirement']}`",
            "",
        ]
    target.write_text("\n".join(lines), encoding="utf-8")


def write_python(target: Path, records: list[dict[str, Any]]) -> None:
    graph_data = {item["component_id"]: item["nodes"] for item in records}
    encoded = json.dumps(graph_data, indent=2, sort_keys=True)
    text = f'''"""Generated ASET 0.4alpha release companion. Semantic precedence: none."""

from __future__ import annotations

GRAPHS = {encoded}


def state(
    subject: str,
    authority: str,
    *,
    recognition: str = "UNKNOWN",
    evidence: tuple[str, ...] = (),
) -> dict[str, object]:
    return {{
        "subject": subject,
        "authority": authority,
        "recognition": recognition,
        "evidence": tuple(sorted(set(evidence))),
    }}


def apply_component(
    current: dict[str, object],
    component_id: str,
    *,
    evidence: str | None = None,
    authority_recognition: frozenset[tuple[str, str, str, str]] = frozenset(),
) -> dict[str, object]:
    result = dict(current)
    for node in GRAPHS[component_id]:
        op = node["op"]
        if op == "INPUT_STATE":
            continue
        if op == "CHECK_RECOGNITION":
            if current["recognition"] != node["value"]:
                raise ValueError("recognition precondition")
        elif op == "REQUIRE_EVIDENCE_ARGUMENT":
            if evidence is None:
                raise ValueError("evidence required")
        elif op == "REQUIRE_OBSERVED_EVIDENCE":
            if evidence not in current["evidence"]:
                raise ValueError("observed evidence required")
        elif op == "REQUIRE_LOCAL_AUTHORITY_WITNESS":
            witness = (
                str(current["authority"]),
                str(current["subject"]),
                evidence,
                str(node["value"]),
            )
            if witness not in authority_recognition:
                raise ValueError("local authority witness required")
        elif op == "ADD_EVIDENCE":
            observed = set(current["evidence"])
            observed.add(evidence)
            result["evidence"] = tuple(sorted(observed))
        elif op == "SET_RECOGNITION":
            result["recognition"] = node["value"]
        elif op == "PRESERVE_STATE":
            continue
        elif op == "RETURN_STATE":
            return result
        else:
            raise ValueError(f"unknown generated graph operation: {{op}}")
    raise ValueError("generated graph has no RETURN_STATE")
'''
    target.write_text(text, encoding="utf-8")


def build_release_profiles(root: Path, output: Path) -> None:
    if output.exists():
        shutil.rmtree(output)
    (output / "en").mkdir(parents=True)
    (output / "python").mkdir(parents=True)
    records = _records(root)
    write_english(output / "en/Seed.md", records)
    write_python(output / "python/aset_seed_alpha4.py", records)
