#!/usr/bin/env python3
from __future__ import annotations

import hashlib
import json
import shutil
from pathlib import Path
from typing import Any

try:
    from tools.alpha4_manifest import parse_seed_manifest
    from tools.alpha4_operational_expression import derive_operational_graphs
except ModuleNotFoundError:
    from alpha4_manifest import parse_seed_manifest
    from alpha4_operational_expression import derive_operational_graphs

ROOT = Path(__file__).resolve().parents[1]


def sha256(path: Path) -> str:
    return "sha256:" + hashlib.sha256(path.read_bytes()).hexdigest()


def _records(root: Path) -> list[dict[str, Any]]:
    bindings = parse_seed_manifest(root)
    pair_by_id = {item.component_id: item for item in bindings.pairs}
    graphs = derive_operational_graphs(root)
    records: list[dict[str, Any]] = []
    for component in graphs["components"]:
        component_id = str(component["component_id"])
        pair = pair_by_id[component_id]
        nodes = component["nodes"]
        rin = next(
            str(node["value"]) for node in nodes if node["op"] == "CHECK_RECOGNITION"
        )
        set_values = [
            str(node["value"]) for node in nodes if node["op"] == "SET_RECOGNITION"
        ]
        rout = set_values[0] if set_values else rin
        ops = {str(node["op"]) for node in nodes}
        if "ADD_EVIDENCE" in ops:
            kind = "OBSERVE_EVIDENCE"
        elif "SET_RECOGNITION" in ops:
            kind = "RECOGNIZE"
        else:
            kind = "PRESERVE"
        records.append(
            {
                "component_id": component_id,
                "operational_word": pair.operational_word,
                "formal_operator": pair.formal_operator,
                "recognition_in": rin,
                "recognition_out": rout,
                "operation_kind": kind,
                "authority_requirement": (
                    "LOCAL_EXACT_SUBJECT_EVIDENCE"
                    if "REQUIRE_LOCAL_AUTHORITY_WITNESS" in ops
                    else "NONE"
                ),
                "nodes": [
                    {key: node[key] for key in ("op", "value") if key in node}
                    for node in nodes
                ],
            }
        )
    return records


def write_english(target: Path, records: list[dict[str, Any]]) -> None:
    lines = [
        "# ASET Seed 0.4alpha — generated ASET Alpha release companion",
        "",
        (
            "Generated by release CI. Seed membership: external companion. "
            "Semantic precedence: none."
        ),
        "",
    ]
    for item in records:
        lines += [
            f"### {item['component_id']}",
            f"Operational: `{item['operational_word']}`",
            f"Relational: `{item['formal_operator']}`",
            f"Recognition: `{item['recognition_in']} -> {item['recognition_out']}`",
            f"Operation: `{item['operation_kind']}`",
            f"Authority: `{item['authority_requirement']}`",
            "",
        ]
    target.write_text("\n".join(lines), encoding="utf-8")


def write_python(target: Path, records: list[dict[str, Any]]) -> None:
    graph_data = {item["component_id"]: item["nodes"] for item in records}
    encoded = json.dumps(graph_data, indent=2, sort_keys=True)
    text = f'''"""Generated ASET 0.4alpha ASET Alpha release companion. Semantic precedence: none."""

from __future__ import annotations

GRAPHS = {encoded}


def state(
    subject: str,
    authority: str,
    *,
    recognition: str = "UNKNOWN",
    evidence: tuple[str, ...] = (),
) -> dict[str, object]:
    return {{
        "subject": subject,
        "authority": authority,
        "recognition": recognition,
        "evidence": tuple(sorted(set(evidence))),
    }}


def apply_component(
    current: dict[str, object],
    component_id: str,
    *,
    evidence: str | None = None,
    authority_recognition: frozenset[tuple[str, str, str, str]] = frozenset(),
) -> dict[str, object]:
    result = dict(current)
    for node in GRAPHS[component_id]:
        op = node["op"]
        if op == "INPUT_STATE":
            continue
        if op == "CHECK_RECOGNITION":
            if current["recognition"] != node["value"]:
                raise ValueError("recognition precondition")
        elif op == "REQUIRE_EVIDENCE_ARGUMENT":
            if evidence is None:
                raise ValueError("evidence required")
        elif op == "REQUIRE_OBSERVED_EVIDENCE":
            if evidence not in current["evidence"]:
                raise ValueError("observed evidence required")
        elif op == "REQUIRE_LOCAL_AUTHORITY_WITNESS":
            witness = (
                str(current["authority"]),
                str(current["subject"]),
                evidence,
                str(node["value"]),
            )
            if witness not in authority_recognition:
                raise ValueError("local authority witness required")
        elif op == "ADD_EVIDENCE":
            observed = set(current["evidence"])
            observed.add(evidence)
            result["evidence"] = tuple(sorted(observed))
        elif op == "SET_RECOGNITION":
            result["recognition"] = node["value"]
        elif op == "PRESERVE_STATE":
            continue
        elif op == "RETURN_STATE":
            return result
        else:
            raise ValueError(f"unknown generated graph operation: {{op}}")
    raise ValueError("generated graph has no RETURN_STATE")
'''
    target.write_text(text, encoding="utf-8")


def write_python_sqlite(target: Path, base_expression_sha256: str) -> None:
    text = f'''"""Generated ASET 0.4alpha Python SQLite persistence extension.

Authority-Seeded Evidence Trail (ASET). ASET Alpha / Local Recognition Algebra.
Semantic delta: none.
"""

from __future__ import annotations

import hashlib
import importlib.util
import json
import sqlite3
from pathlib import Path
from typing import Any

BASE_EXPRESSION_SHA256 = {base_expression_sha256!r}
BASE_EXPRESSION_PATH = (
    Path(__file__).resolve().parents[1] / "python" / "aset_seed_alpha4.py"
)


def _sha256(path: Path) -> str:
    return "sha256:" + hashlib.sha256(path.read_bytes()).hexdigest()


def _load_base_expression() -> Any:
    if _sha256(BASE_EXPRESSION_PATH) != BASE_EXPRESSION_SHA256:
        raise RuntimeError("base Python expression byte identity mismatch")
    spec = importlib.util.spec_from_file_location(
        "aset_seed_alpha4_base_expression",
        BASE_EXPRESSION_PATH,
    )
    if spec is None or spec.loader is None:
        raise RuntimeError("base Python expression cannot be loaded")
    module = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(module)
    return module


_base_expression = _load_base_expression()


def _encode_evidence(value: object) -> str:
    return json.dumps(list(value), separators=(",", ":"), ensure_ascii=True)


def _decode_evidence(value: str) -> tuple[str, ...]:
    decoded = json.loads(value)
    if not isinstance(decoded, list) or not all(
        isinstance(item, str) for item in decoded
    ):
        raise ValueError("stored evidence payload is invalid")
    return tuple(decoded)


def _read_state(connection: sqlite3.Connection) -> dict[str, object]:
    row = connection.execute(
        "SELECT subject, authority, recognition, evidence_json "
        "FROM seed_state WHERE id = 1"
    ).fetchone()
    if row is None:
        raise ValueError("persistent Seed state is not initialized")
    return {{
        "subject": row[0],
        "authority": row[1],
        "recognition": row[2],
        "evidence": _decode_evidence(row[3]),
    }}


def _write_state(
    connection: sqlite3.Connection,
    current: dict[str, object],
) -> None:
    connection.execute(
        "INSERT INTO seed_state "
        "(id, subject, authority, recognition, evidence_json) "
        "VALUES (1, ?, ?, ?, ?) "
        "ON CONFLICT(id) DO UPDATE SET "
        "subject = excluded.subject, "
        "authority = excluded.authority, "
        "recognition = excluded.recognition, "
        "evidence_json = excluded.evidence_json",
        (
            str(current["subject"]),
            str(current["authority"]),
            str(current["recognition"]),
            _encode_evidence(current["evidence"]),
        ),
    )


class SQLiteStore:
    def __init__(self, path: str | Path) -> None:
        self.path = Path(path)
        self.path.parent.mkdir(parents=True, exist_ok=True)
        with self._connect() as connection:
            connection.execute(
                "CREATE TABLE IF NOT EXISTS seed_state ("
                "id INTEGER PRIMARY KEY CHECK (id = 1), "
                "subject TEXT NOT NULL, "
                "authority TEXT NOT NULL, "
                "recognition TEXT NOT NULL, "
                "evidence_json TEXT NOT NULL"
                ")"
            )

    def _connect(self) -> sqlite3.Connection:
        return sqlite3.connect(self.path)

    def initialize(self, current: dict[str, object]) -> None:
        with self._connect() as connection:
            connection.execute("BEGIN IMMEDIATE")
            _write_state(connection, current)

    def load(self) -> dict[str, object]:
        with self._connect() as connection:
            return _read_state(connection)

    def apply_component(
        self,
        component_id: str,
        *,
        evidence: str | None = None,
        authority_recognition: frozenset[tuple[str, str, str, str]] = frozenset(),
    ) -> dict[str, object]:
        with self._connect() as connection:
            connection.execute("BEGIN IMMEDIATE")
            current = _read_state(connection)
            result = _base_expression.apply_component(
                current,
                component_id,
                evidence=evidence,
                authority_recognition=authority_recognition,
            )
            _write_state(connection, result)
            return result
'''
    target.write_text(text, encoding="utf-8")


def write_python_sqlite_binding(
    target: Path,
    base_expression: Path,
    extension: Path,
) -> None:
    value = {
        "document_type": "aset-python-persistence-extension-binding",
        "extension_id": "ASET-PYTHON-SQLITE-PERSISTENCE-V1",
        "relation": "PERSISTENCE_EXTENSION",
        "semantic_delta": "NONE",
        "semantic_precedence": "NONE",
        "base_expression": {
            "profile": "python",
            "path": "python/aset_seed_alpha4.py",
            "sha256": sha256(base_expression),
        },
        "extension": {
            "profile": "python-sqlite",
            "path": "python-sqlite/aset_seed_alpha4_sqlite.py",
            "sha256": sha256(extension),
            "storage_backend": "python-stdlib-sqlite3",
        },
        "assurance_scope": [
            "EXACT_BASE_EXPRESSION_BYTE_BINDING",
            "BASE_EXPRESSION_OBSERVATIONAL_CONGRUENCE",
            "ATOMIC_SUCCESSFUL_COMMIT",
            "ROLLBACK_ON_BASE_EXPRESSION_REJECTION",
            "RESTART_ROUND_TRIP",
        ],
        "not_claimed": [
            "UNIVERSAL_CONCURRENCY_CORRECTNESS",
            "STORAGE_CORRUPTION_RECOVERY",
        ],
    }
    target.write_text(
        json.dumps(value, indent=2, sort_keys=True) + "\n",
        encoding="utf-8",
    )


def build_release_profiles(root: Path, output: Path) -> None:
    if output.exists():
        shutil.rmtree(output)
    (output / "en").mkdir(parents=True)
    (output / "python").mkdir(parents=True)
    (output / "python-sqlite").mkdir(parents=True)
    records = _records(root)
    write_english(output / "en/Seed.md", records)
    base_expression = output / "python/aset_seed_alpha4.py"
    extension = output / "python-sqlite/aset_seed_alpha4_sqlite.py"
    binding = output / "python-sqlite/PERSISTENCE_EXTENSION.json"
    write_python(base_expression, records)
    write_python_sqlite(extension, sha256(base_expression))
    write_python_sqlite_binding(binding, base_expression, extension)
